seed: 19961103
random_tp_range: 1000

fast_reset: True
start_time: 0
time_limit: 3000
candidate_preferred_spawn_biome:
  - plains
candidate_weather:
  - clear

camera_config:
  camera_binsize: 1
  camera_maxval: 10
  camera_mu: 20
  camera_quantization_scheme: "mu_law"

origin_resolution: [640, 360]
resize_resolution: [640, 360]

need_crafting_table: False
need_gui: False
inventory_distraction_level: "low"

task_conf:
  - name: "mine"
    text: "mine_block:nether_gold_ore"

reward_conf:
  - event: "mine_block"
    max_reward_times: 2
    reward: 1.0
    objects:
      - "nether_gold_ore"
    identity: "mine 2 nether gold ore" 

init_inventory:
  - slot: 0
    type: iron_pickaxe
    quantity: 1
  - slot: 1
    type: torch
    quantity: 16

mobs: []

worker:
  "mine"
