seed: 19961103
random_tp_range: 1000

fast_reset: True
start_time: 0
time_limit: 2000
candidate_preferred_spawn_biome:
  - plains
candidate_weather:
  - clear

camera_config:
  camera_binsize: 1
  camera_maxval: 10
  camera_mu: 20
  camera_quantization_scheme: "mu_law"

origin_resolution: [640, 360]
resize_resolution: [640, 360]

need_crafting_table: True
need_gui: True
inventory_distraction_level: "low"

task_conf:
  - name: "craft"
    text: "craft_item:golden_apple"

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects:
      - "golden_apple"
    identity: "craft golden_apple"

init_inventory:
  - slot: 0
    type: gold_ingot
    quantity: 8
  - slot: 1
    type: apple
    quantity: 1
  - slot: 9
    type: iron_ingot
    quantity: 4

mobs: []

worker:
  "craft"
