defaults:
  - base
  - _self_

candidate_preferred_spawn_biome:
  - plains

task_conf:
  - name: "craft"
    text: "craft_item:wooden_sword"

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects:
      - "wooden_sword"
    identity: "craft wooden_sword"

need_crafting_table: True
need_gui: True

init_inventory:
  - slot: 0
    type: oak_planks
    quantity: 6
  - slot: 1
    type: stick
    quantity: 1

