defaults:
  - base
  - _self_

candidate_preferred_spawn_biome:
  - plains

task_conf:
  - name: "craft"
    text: "craft_item:furnace"

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects:
      - "furnace"
    identity: "craft furnace"

need_crafting_table: True
need_gui: True

init_inventory:
  - slot: 0
    type: cobblestone
    quantity: 8
  - slot: 1
    type: oak_planks
    quantity: 4
  - slot: 2
    type: crafting_table
    quantity: 1
