defaults:
  - base
  - _self_

seed: 4143222138124291041
command: []

task_conf:
  - name: "kill_entity"
    text: "kill_entity:cow"

reward_conf:
  - event: "kill_entity"
    max_reward_times: 1
    reward: 1.0
    objects:
      - "cow"
    identity: "kill cow"

mobs:
  - name: "cow"
    number: 1
    range_x: [-2, 2]
    range_z: [3, 10]
  - name: "cow"
    number: 1
    range_x: [2, 2]
    range_z: [3, 10]

init_inventory:
  - slot: 0
    type: "diamond_sword"
    quantity: 1
