seed: 3001859308298079279
random_tp_range: 1000

fast_reset: True
start_time: 0
time_limit: 3500
candidate_preferred_spawn_biome:
  - plains
preferred_spawn_biome: "plains"
candidate_weather:
  - clear

command:
  - "/time set night"

camera_config:
  camera_binsize: 1
  camera_maxval: 10
  camera_mu: 20
  camera_quantization_scheme: "mu_law"

origin_resolution: [640, 360]
resize_resolution: [640, 360]

need_crafting_table: False
need_gui: False
inventory_distraction_level: "zero"

task_conf:
  - name: "kill_entity"
    text: "kill_entity:zombie and kill_entity:skeleton"

reward_conf:
  - event: "kill_entity"
    max_reward_times: 3
    reward: 0.5
    objects:
      - "zombie"
    identity: "kill 3 zombies"
  - event: "kill_entity"
    max_reward_times: 3
    reward: 0.5
    objects:
      - "skeleton"
    identity: "kill 3 skeletons" 

mobs:
  - name: "zombie"
    number: 4
    range_x: [-5,-1]
    range_z: [3,12]
  - name: "skeleton"
    number: 4
    range_x: [1, 5]
    range_z: [3,12]

init_inventory:
  - slot: 0
    type: "iron_sword"
    quantity: 1
  - slot: 1
    type: "shield"
    quantity: 1

worker:
  "mine"
