defaults:
  - base
  - _self_

candidate_preferred_spawn_biome:
  - "jungle"

task_conf:
  - name: "mine"
    text: "mine_block:mossy_cobblestone"

reward_conf:
  - event: "mine_block"
    max_reward_times: 1
    reward: 1.0
    objects:
      - "mossy_cobblestone"
    identity: "mine mossy_cobblestone"

init_inventory:
  - slot: 0
    type: wooden_pickaxe
    quantity: 1

